version: '3'
services:
  server:
    platform: linux/amd64
    build:
      context: server
      dockerfile: Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  flow:
    platform: linux/amd64
    build:
      context: flow
      dockerfile: Dockerfile
    volumes:
      - ./flow:/flow
    depends_on:
      - server
