version: '3'
services:
  server:
    build:
      context: server
      dockerfile: Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  flow:
    build: .
    volumes:
      - .:/app
    depends_on:
      - server
