version: '3.8'

x-template: &template
  platform: linux/amd64
  build:
    context: .
    dockerfile: Dockerfile
    args:
      - PREFECT_PROJECT_NAME=etude-Prefect
  environment:
    - PREFECT_PROJECT_NAME=etude-Prefect
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock

services:
  server:
    <<: *template
    build:
      context: server

  agent:
    <<: *template
    build:
      context: agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - flows_storage:/root/.prefect/flows
    depends_on:
      - server

  flow:
    <<: *template
    build:
      context: flow
    volumes:
      - ./flow:/flow
      - flows_storage:/root/.prefect/flows
    depends_on:
      - server

volumes:
  flows_storage:
